### ISSUE TITLE
Java 23 support

### ISSUE THREAD

**Issue by boris-petrov** [autonomousapps/dependency-analysis-gradle-plugin#1297]
**Is your feature request related to a problem? Please describe.**
I can't use `dependency-analysis-gradle-plugin ` with Java 23:

```
Execution failed for task ':my-project:explodeJarMain'.
> A failure occurred while executing com.autonomousapps.tasks.ExplodeJarTask$ExplodeJarWorkAction
   > Unsupported class file major version 67
```

```
...
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 67
        at com.autonomousapps.internal.asm.ClassReader.<init>(ClassReader.java:200)
        at com.autonomousapps.internal.asm.ClassReader.<init>(ClassReader.java:180)
        at com.autonomousapps.internal.asm.ClassReader.<init>(ClassReader.java:166)
        at com.autonomousapps.internal.JarExploder$explode$visitors$1.invoke(JarExploder.kt:71)
        at com.autonomousapps.internal.JarExploder$explode$visitors$1.invoke(JarExploder.kt:69)
        ...
```

**Describe the solution you'd like**
Please update the used ASM version to 9.7.1. That will resolve the issue.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by autonomousapps** [comment]
Thanks for the issue. This should be fixed in the next release.
