### ISSUE TITLE
Add support for project isolation

### ISSUE THREAD

**Issue by NikolayMetchev** [autonomousapps/dependency-analysis-gradle-plugin#1317]
**Is your feature request related to a problem? Please describe.**
I would like to use project isolation in our build and use the dependency analysis gradle plugin
Project isolation is described here:
https://docs.gradle.org/current/userguide/isolated_projects.html

**Describe the solution you'd like**
Make the necessary changes to make this plugin compliant.

**Describe alternatives you've considered**
None available

**Additional context**
Here is the first problem encountered when I tried to use project isolation:
```
- [error] Project `:buildSrc` cannot access `Project.plugins` functionality on another project `:`
    - plugin 'com.autonomousapps.dependency-analysis'
        - Exception at `com.autonomousapps.services.InMemoryCache$Companion.serviceHoldingBuild(InMemoryCache.kt:76)`
org.gradle.api.InvalidUserCodeException: Project ':buildSrc' cannot access 'Project.plugins' functionality on another project ':'
	at org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject_Decorated.getPlugins(Unknown Source)
	at com.autonomousapps.services.InMemoryCache$Companion.serviceHoldingBuild(InMemoryCache.kt:76)
	at com.autonomousapps.services.InMemoryCache$Companion.register$dependency_analysis_gradle_plugin(InMemoryCache.kt:90)
	at com.autonomousapps.internal.analyzer.JvmAnalyzer$registerFindDeclaredProcsTask$1.invoke(JvmProjectAnalyzer.kt:72)
	at com.autonomousapps.internal.analyzer.JvmAnalyzer$registerFindDeclaredProcsTask$1.invoke(JvmProjectAnalyzer.kt:71)
	at com.autonomousapps.internal.analyzer.JvmAnalyzer$inlined$sam$i$org_gradle_api_Action$0.execute(TaskContainerExtensions.kt)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at com.intellij.gradle.toolingExtension.impl.model.warmUp.GradleTaskWarmUpService.lambda$buildAll$2(GradleTaskWarmUpService.java:34)
	at com.intellij.gradle.toolingExtension.impl.util.GradleResultUtil.lambda$runOrRetryOnce$0(GradleResultUtil.java:34)
	at com.intellij.gradle.toolingExtension.impl.util.GradleResultUtil.runOrRetryOnce(GradleResultUtil.java:16)
	at com.intellij.gradle.toolingExtension.impl.util.GradleResultUtil.runOrRetryOnce(GradleResultUtil.java:33)
	at com.intellij.gradle.toolingExtension.impl.model.warmUp.GradleTaskWarmUpService.buildAll(GradleTaskWarmUpService.java:33)
	at com.intellij.gradle.toolingExtension.impl.modelBuilder.ExtraModelBuilder.buildServiceModel(ExtraModelBuilder.java:87)
	at com.intellij.gradle.toolingExtension.impl.modelBuilder.ExtraModelBuilder.buildAll(ExtraModelBuilder.java:67)
	at com.intellij.gradle.toolingExtension.impl.modelBuilder.ExtraModelBuilder.buildAll(ExtraModelBuilder.java:47)
```

**Comment by autonomousapps** [comment]
This plugin does already support Isolated Projects (Gradle itself has confirmed this, as they use the plugin in their own builds). Do you have a minimal reproducer?

**Comment by NikolayMetchev** [comment]
Ok. this bug is really strange. It only reproduces in Idea. If you run gradle on its own everything is fine.  I have attached a project that when you open in Idea should fail.
[deps-bug.zip](https://github.com/user-attachments/files/17869025/deps-bug.zip)

**Comment by NikolayMetchev** [comment]
yes

**Comment by NikolayMetchev** [comment]
We're also hitting this on a large Kotlin monorepo (391 projects) with Gradle 9.5 and `org.gradle.unsafe.isolated-projects=true` in `gradle.properties`.

The specific violation:

```
Plugin 'com.autonomousapps.dependency-analysis': Project ':buildSrc' cannot access 'Project.plugins' functionality on another project ':'
```

This is the only remaining isolation violation in our build after eliminating all others. We're currently working around it with `org.gradle.configuration-cache.problems=warn` in `gradle.properties`, which downgrades the error to a warning.

- dependency-analysis: 3.12.0
- Gradle: 9.5
- Kotlin: 2.3.20

**Comment by autonomousapps** [comment]
@NikolayMetchev and that reproduces with the reproducer you attached at https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1317#issuecomment-2493483127 ?

**Comment by autonomousapps** [comment]
Also, could you provide the html report on the IP failure?

**Comment by autonomousapps** [comment]
Ok, I know the cause. Unfortunately, it's a workaround of https://github.com/gradle/gradle/issues/17559 to better support shared build services. I'll see what I can do to address it. Contributions also welcome.

```kotlin
    /**
     * Determines the build on which to register the service. In a composite build, the root build is used to share the
     * cache across builds if the root build used that same classloader for loading the plugin as the current build.
     * See: https://github.com/gradle/gradle/issues/17559
     */
    private fun Project.serviceHoldingBuild(): Gradle {
      val thisBuild = gradle
      val rootBuild = thisBuild.rootBuild()

      if (thisBuild == rootBuild) {
        return thisBuild
      }

      val thisPluginInstance = thisBuild.rootProject.plugins.findPlugin(DependencyAnalysisPlugin.ID)
      val rootPluginInstance = rootBuild.rootProject.plugins.findPlugin(DependencyAnalysisPlugin.ID)

      if (thisPluginInstance == null || rootPluginInstance == null) {
        return thisBuild
      }

      return if (thisPluginInstance::class.java == rootPluginInstance::class.java) {
        rootBuild // shared cache in the root if plugin was loaded with same classloader
      } else {
        thisBuild
      }
    }

    fun register(project: Project): Provider<InMemoryCache> = project
      .serviceHoldingBuild()
      .sharedServices
      .registerIfAbsent(SHARED_SERVICES_IN_MEMORY_CACHE, InMemoryCache::class.java) {
        it.parameters.cacheSize.set(project.cacheSize(DEFAULT_CACHE_VALUE))
      }
```

**Comment by jjohannes** [comment]
This issue can only trigger in a composite build (or build with buildSrc) where one of the non-root builds (e.g. buildSrc) uses DAGP. I think that is why not more users have this problem.

The general idea is to have only one `InMemoryCache` cache for the whole build tree in a composite build scenario.

However, it may not be possible if the DAGP has been loaded multiple-times. Which ideally should not happen, but you can get there if the plugin is applied differently in different (sub)projects of the tree. That's why this check is there to fall back to having separate caches – and not get a weird class cast exception. I think in the case of using DAGP in buildSrc, you'll always have this situation, which is expected.

This optimization is for cases where the "main" build is composed of multiple builds that depend on each other and thus can profit from the shared cache.

Instead of `findPlugin` we can probably get hold of the _plugin classloader_ of `thisBuild.rootProject` vs `rootBuild.rootProject` in a way that does not violate project isolation. And then we can check if the classloaders are the same or not.

**Comment by NikolayMetchev** [comment]
Thank you
