### ISSUE TITLE
Unsupported class file major version error without class file name

### ISSUE THREAD

**Issue by ianbrandt** [autonomousapps/dependency-analysis-gradle-plugin#965]
**Build scan link**
https://scans.gradle.com/s/ozlm4ja7xdxp4

**Plugin version**
1.22.0

**Gradle version**
8.3

**(Optional) Android Gradle Plugin (AGP) version**
N/A

**`reason` output for bugs relating to incorrect advice**
N/A

**Describe the bug**
I'm getting an "Unsupported class file major version 65" error from `com.autonomousapps.internal.asm.ClassReader` when running `buildHealth` under Java 17, but it doesn't include information on the class file that triggered the error.

**To Reproduce**
1. Run `buildHealth` on https://github.com/sdkotlin/sd-kotlin-spring-talks/tree/b6fef066474732ac3179e129e01124fc8c472301 with JDK 17.

```text
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':subprojects:app:explodeJarTest'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)
[...]
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
	at com.autonomousapps.internal.asm.ClassReader.<init>(ClassReader.java:199)
	at com.autonomousapps.internal.asm.ClassReader.<init>(ClassReader.java:180)
	at com.autonomousapps.internal.asm.ClassReader.<init>(ClassReader.java:166)
	at com.autonomousapps.internal.JarExploder$explode$visitors$1.invoke(JarExploder.kt:72)
	at com.autonomousapps.internal.JarExploder$explode$visitors$1.invoke(JarExploder.kt:70)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesJvmKt.toSortedSet(_SequencesJvm.kt:48)
	at com.autonomousapps.internal.JarExploder.explode(JarExploder.kt:97)
	at com.autonomousapps.internal.JarExploder.access$explode(JarExploder.kt:15)
	at com.autonomousapps.internal.JarExploder$toExplodedJars$1.invoke(JarExploder.kt:39)
	at com.autonomousapps.internal.JarExploder$toExplodedJars$1.invoke(JarExploder.kt:37)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesJvmKt.toSortedSet(_SequencesJvm.kt:48)
	at com.autonomousapps.internal.JarExploder.toExplodedJars(JarExploder.kt:48)
	at com.autonomousapps.internal.JarExploder.explodedJars(JarExploder.kt:33)
	at com.autonomousapps.tasks.ExplodeJarTask$ExplodeJarWorkAction.execute(ExplodeJarTask.kt:90)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
[...]
```

**Expected behavior**
I did just update this project to milestone versions of Spring, Spring Boot, and the Spring Gradle Plugin, so it's probably caused by one of those or their transitive dependencies having been compiled for Java 21. That's a large search space given the stack trace doesn't specify which class file caused the error. If the plugin could catch the exception thrown by `com.autonomousapps.internal.asm.ClassReader` somewhere up the stack where the class file name is available, and throw a wrapping exception that contains that information, that would be very helpful.

**Comment by autonomousapps** [comment]
Thanks for the issue, and I appreciate the reproducer as well. This kind of thing comes up from time to time and can usually be fixed by updating the version of asm the project uses.

**Comment by autonomousapps** [comment]
I cloned your project and ran `buildHealth` with a modified version and here's info on the classfile causing trouble:
```
> Task :subprojects:child-context:domain-service:findInlineMembersMain FAILED
Failed on META-INF/versions/21/org/springframework/core/task/VirtualThreadDelegate.class in ~/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/6.1.0-M5/d47f7f4a50db825c0274fc66a0a914ef4170775a/spring-core-6.1.0-M5.jar
```
I'm assuming I can resolve this with a newer ASM, but I like your idea of wrapping calls to `ClassReader()` to get more information, so I may do that as well.

**Comment by autonomousapps** [comment]
I can confirm that using a later version of asm resolves the issue.

**Comment by ianbrandt** [comment]
Many thanks. 1.24.1-SNAPSHOT works on my machine. I am now getting some unexpected advice, but I'll investigate and file that separately if necessary.
