### ISSUE TITLE
Stop using deprecated BuildIdentifier.getName() call

### ISSUE THREAD

**Issue by Mahoney** [autonomousapps/dependency-analysis-gradle-plugin#994]
**Is your feature request related to a problem? Please describe.**

When I run `gw --no-build-cache clean buildHealth` I get the dreaded "Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0."

Running `gw --no-build-cache --warning-mode all --stacktrace clean buildHealth` I see that the culprit is:

```
> Task :graphViewMain
The BuildIdentifier.getName() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Use getBuildPath() to get a unique identifier for the build. Consult the upgrading guide for further information: https://docs.gradle.org/8.4/userguide/upgrading_version_8.html#build_identifier_name_and_current_deprecation
        at org.gradle.api.internal.artifacts.DefaultBuildIdentifier.getName(DefaultBuildIdentifier.java:48)
        at com.autonomousapps.internal.utils.GradleStringsKt.toCoordinates(gradleStrings.kt:103)
        at com.autonomousapps.internal.utils.GradleStringsKt.rootCoordinates(gradleStrings.kt:95)
        at com.autonomousapps.internal.utils.GradleStringsKt.rootCoordinates(gradleStrings.kt:89)
        at com.autonomousapps.internal.graph.GraphViewBuilder.<init>(GraphViewBuilder.kt
```

**Describe the solution you'd like**

The deprecation message says:
Use getBuildPath() to get a unique identifier for the build. Consult the upgrading guide for further information: https://docs.gradle.org/8.4/userguide/upgrading_version_8.html#build_identifier_name_and_current_deprecation

So I guess that? Not sure exactly what you are using `BuildIdentifier.getName()` for, so hard to know how easy it is to follow that advice.

**Additional context**
Gradle 8.4
com.autonomousapps.dependency-analysis 1.25.0

**Comment by autonomousapps** [comment]
We have some TODOs in the project for this. But please note that this plugin supports down to Gradle 7.4, where that method call is _not_ deprecated. What we'll have to do is implement runtime checks to use the right method with the right version.

cc @jjohannes

**Comment by jjohannes** [comment]
I completely missed this. Thanks for the ping. If all tests pass, this hopefully fixes it consistently: #995
